# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RatingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('userurl', models.TextField()),
                ('rating', models.FloatField()),
                ('review', models.TextField()),
                ('restaurantname', models.TextField()),
                ('restauranturl', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('expensivelevel', models.IntegerField()),
                ('reviewcount', models.IntegerField()),
                ('url', models.TextField()),
                ('category', models.TextField()),
                ('current_rating', models.FloatField()),
                ('city', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
    ]
